backend/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from information.views import IndexView

static_urlpatterns = [

]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('information/', include('information.urls', namespace='information')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cosmicstore/', include('store.urls', namespace='cosmostore')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('api-token-auth/', views.obtain_auth_token),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/blog/urls.py
from django.urls import path

from blog.views import BlogListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
]

backend/information/urls.py
from django.urls import path

from information.views import ContactView, ProjectsView, StackView

app_name = 'information'

urlpatterns = [
    path('contact', ContactView.as_view(), name='contact'),
    path('stack', StackView.as_view(), name='stack'),
    path('projects', ProjectsView.as_view(), name='projects')

]

backend/tools/urls.py
from django.urls import path, include
from tools.views import converter_currencies, conventer_to_pdf

app_name = 'tools'

urlpatterns = [
    path('converter', converter_currencies, name='converter'),
    path('converter_to_pdf', conventer_to_pdf, name='converter_to_pdf'),
]

backend/information/views.py
from django.views.generic.base import TemplateView

from common.views import TitleMixin
from common.weather_time import WeatherMixin


class IndexView(TitleMixin, WeatherMixin, TemplateView):
    template_name = 'information/index.html'
    title = 'Главная страница'


class ContactView(TitleMixin, TemplateView):
    template_name = 'information/contact.html'
    title = 'Контакты'


class ProjectsView(TitleMixin, TemplateView):
    template_name = 'information/projects.html'
    title = 'Проекты'


class StackView(TitleMixin, TemplateView):
    template_name = 'information/stack.html'
    title = 'Стак технологий'

backend/information/templates/information/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Портфолио</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> <!-- https://fonts.google.com/ -->
    <link rel="stylesheet" href=" {% static '/vendor/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static '/vendor/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static '/vendor/css/template.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/index.css' %}">
    <link rel="stylesheet" href={% static '/vendor/bootstrap/css/bootstrap.css' %}>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="icon" href="{% static '/vendor/icon.png' %}" type="image/x-icon">

    {% block css %} {% endblock %}

</head>



<body style="overflow: hidden; min-height: 100vh; height: 100%; z-index: -10" id="intro">


<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

        <a class="navbar-brand "   href="{% url 'index' %}">
            Сайт Ермишова Н.И.
        </a>
</nav>

{% block content %} {% endblock %}




    <script src=" {% static '/vendor/js/three.min.js' %}"></script>
    <script src=" {% static '/vendor/js/vanta.net.min.js' %}"></script>
    <script src=" {% static '/vendor/js/app.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/01de7652a2.js" crossorigin="anonymous"></script>

</body>



</html>

backend/information/templates/information/contact.html
{% extends 'information/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
<section>
<div align="center">
    <div  class="tm-container" style="padding-top: 200px; margin: 0; padding-bottom: 50px">
        <div align="center" class="tm-main-nav" >
            <ul style="align-items: center; justify-content: center">
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="tel:+79168071904" data-effect="mfp-move-from-top" class="tm-nav-link" target="_blank">
                        <p><i style="color: #6A5ACD" class="fa-solid fa-5x fa-phone"></i></p>
                        <p style="color: #FFFFFF">+7-(916)-807-19-04</p>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="mailto:nikita321@bk.ru" data-effect="mfp-move-from-top" class="tm-nav-link" target="_blank">
                        <p><i style="color: #6A5ACD" class="fa-regular fa-5x fa-envelope"></i></p>
                        <p style="color: #FFFFFF">nikita321@bk.ru</p>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="https://t.me/Chikcharyk" data-effect="mfp-move-from-top" class="tm-nav-link" target="_blank">
                        <p><i style="color: #6A5ACD" class="fa-brands fa-5x fa-telegram" ></i>
                        <p style="color: #FFFFFF">@Chikcharyk</p>
                        <h1></h1>
                        <h2></h2>
                        <p align="center" style="color: black">*предпочитаемый способ связи</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
</section>
{% endblock %}

backend/information/templates/information/index.html
{% extends 'information/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
<section style="height: 100%">


    <div style="
    margin-top: 80px;
    margin-right: 10%;
    float: right;
    height: 60px;
    width: 300px;
    background: linear-gradient(to top left, #310062,#310062);
    border-radius: 10px
    " >
        <div style="margin-top: 5px">
            <div style="float: left; color: #6A5ACD; margin-left: 10px"
            > <i class="fa-solid fa-3x fa-circle-info"></i></div>
            <div style="color: white" align="center">
                 Температура в Москве {{ current_temp }}°
            </div>
            <div style="color: white" align="center">
                Сейчас {% now "j E H:i" %}
            </div>
        </div>
    </div>

    <div class="tm-container" style="padding-top: 200px; margin-top: 50px; padding-bottom: 50px">
        <nav class="tm-main-nav" style="height: 100%">
            <ul>
                <li class="tm-nav-item" style="border-radius: 50px; border: none;">
                    <a href="{% url 'information:projects' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation">
                            Проекты
                        </span>
                        <i style="color: #6A5ACD" class="fa-solid fa-5x fa-code"></i>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'information:stack' %}" data-effect="mfp-move-from-top" class="tm-nav-link" id="tm-gallery-link">
                        <span class="cursor typewriter-animation">
                            Стек технологий
                        </span>
                        <i style="color: #6A5ACD" class="fa-solid fa-5x fa-microchip"></i>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'cosmostore:index' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation">
                            Магазин
                        </span>
                        <i style="color: #6A5ACD" class="fa fa-5x fa-shopping-bag"></i>
                    </a>
                </li>

                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'blog:blog' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation">
                            Бложик
                        </span>

                        <i style="color: #6A5ACD" class="fa-regular fa-5x fa-newspaper"></i>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'information:contact' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation">
                            Контакты
                        </span>
                        <i style="color: #6A5ACD" class="fa fa-5x fa-address-card"></i>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'tools:converter' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation" style="font-size: 18px">
                            Конвентер валют
                        </span>
                        <i style="color: #6A5ACD" class="fa fa-5x fa-money-bill"></i>
                    </a>
                </li>
                <li class="tm-nav-item" style="border-radius: 50px; border: none">
                    <a href="{% url 'tools:converter_to_pdf' %}" data-effect="mfp-move-from-top" class="tm-nav-link">
                        <span class="cursor typewriter-animation" style="font-size: 18px">
                            Word в PDF
                        </span>
                        <i style="color: #6A5ACD" class="fa fa-5x fa-money-bill"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
</section>
{% endblock %}

backend/information/templates/information/projects.html
{% extends 'information/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
    <section  style="height: 100%">
      <div align="center" >
          <div style="margin-bottom: 10%">
          </div>
          <div style="background: rgba(0, 0, 0, 0.5)">
            <p ><i style="color: #46007e; padding-top: 20px" class="fa-solid fa-5x fa-code"></i></p>
            <h1 style="color: #46007e">
              Мои пет-проекты:
            </h1>
            <br >
          </div>
        <div style="background: rgba(0, 0, 0, 0.5)">
          <ol style="font-size: 30px;">
            <li style="color: #46007e; font-family: FontName">Сайт на котором Вы находитесь. (Ссылку на гитхаб предоставлю при запросе)</li>
              <li></li>
            <li style="color: #46007e; font-family: FontName"> <a href="https://github.com/KitaRomanov/django_learn_project.git">Проект интернет магазина</a> </li>
            <li></li>
            <li style="color: #46007e; font-family: FontName"> <a href="https://github.com/KitaRomanov/game_FAEW">Простенькая игра</a> </li>
            <li></li>
              <li style="color: #46007e; font-family: FontName"> <a href="https://t.me/lie_weather_bot" >Телеграмм бот подключенный к API магазина, выдает товары<a/> </li>
              <li></li>
          </ol>
        </div>
      </div>

    </section>
{% endblock %}

backend/information/templates/information/stack.html
{% extends 'information/base.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
    <section>
    <div style="margin-bottom: 10%"></div>
  <div align="center">
      <div style="background: rgba(0, 0, 0, 0.5)">
          <h1 style="color: #46007e; font-family: FontName">
            Стек технологий, которыми я владею:
          </h1>
            <br>
      </div>
    <div style="background: rgba(0, 0, 0, 0.5)">
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-brands fa-python"></i>   Язык программирования: Python</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"> Unit tests</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-solid fa-database"></i>   Базы данных: PostgreSQL, SQLite, Redis</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"> Django</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName">Celery</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-brands fa-github"></i> Git</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-brands fa-linux"> <i style="color: #46007e" class="fa-brands fa-ubuntu"></i> </i> Linux (Ubuntu)</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-solid fa-a"></i><i style="color: #46007e" class="fa-solid fa-p"></i><i style="color: #46007e" class="fa-solid fa-i"></i> REST API</p>
      <p style="font-size: 35px; color: #46007e; font-family: FontName"><i style="color: #46007e" class="fa-brands fa-html5"></i> <i style="color: #46007e" class="fa-brands fa-css3-alt"></i> HTML/CSS</p>
    </div>
  </div>
</section>
{% endblock %}