backend/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from information.views import IndexView

static_urlpatterns = [

]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('information/', include('information.urls', namespace='information')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cosmicstore/', include('store.urls', namespace='cosmostore')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('api-token-auth/', views.obtain_auth_token),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import path

from store.views import ProductsListView, basket_add, basket_remove

app_name = 'store'
urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    # path('category/<int:category_id>', ProductsListView.as_view(), name='category'), #категории пока не требуются
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

backend/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from users.views import (EmailVerificationView, LogoutCustomView,
                         UserLoginView, UserProfileView, UserRegistrationView)

app_name = 'users'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registrations/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutCustomView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
]

backend/store/models.py
from django.db import models

from users.models import User


class ProductCategory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    class Meta():
        verbose_name = 'категории'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class ProductPromo(models.Model):
    promo = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)

    class Meta():
        verbose_name = 'акция'
        verbose_name_plural = 'акция'

    def __str__(self):
        return self.promo


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images', null=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    promo = models.ForeignKey(to=ProductPromo, on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return f'Продукт:  {self.name} | Категория {self.category.name}'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    @classmethod
    def create_or_update(cls, product_id, user):
        baskets = Basket.objects.filter(user=user, product_id=product_id)

        if not baskets.exists():
            obj = Basket.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
            is_created = False
            return basket, is_created

backend/store/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.views.generic.list import ListView

from common.views import TitleMixin
from store.models import Basket, Product


class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'store/main_page.html'
    # paginate_by = 6    #Пока не требуется добавлю позже
    title = 'Космикстор'

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset


@login_required
def basket_add(request, product_id):
    Basket.create_or_update(product_id, request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

backend/store/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href=" {% static 'store/css/store_main.css' %}">
    <link rel="stylesheet" href="{% static 'store/fonts/stylesheet.css' %}">
    <style>body { margin: 0; }</style>

</head>
<body class="main_brand" background="{% static 'store/back.jpg' %}">
<div class="nav_brand">
           <a href="{% url 'store:index' %}"><img class="icon" src=" {% static 'store/cosmicstore.png' %}"></a>
            {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}" ><i class="fa-solid fa-4x fa-right-from-bracket " style="float: right; margin-right: 5%; color: black"></i></a>
                <a href="{% url 'users:profile' user.id %}" ><img src="{% static 'store/icon_lc.png' %}" class="icon" style="float: right; margin-right: 2%"></a>
            {% else %}
                <a href="{% url 'users:login' %}" ><img src="{% static 'store/icon_lc.png' %}" class="icon" style="float: right; margin-right: 5%"></a>
            {% endif %}

</div>
</body>
{% block content %} {% endblock %}

                <script src="https://unpkg.com/@popperjs/core@2"></script>
                <script src="https://unpkg.com/tippy.js@6"></script>
                <script type="text/javascript" src="{% static "store/js/script.js" %}"></script>
                <script src="https://kit.fontawesome.com/01de7652a2.js" crossorigin="anonymous"></script>
                <script>
                    $(function(){
	                    $("#message").delay(5000).slideUp(300);
                    });
                </script>


</html>

backend/store/templates/store/baskets.html
{% if baskets %}

      <div align="center">
         <p class="text" style="margin-bottom: 0; font-size: 30px">Корзина </p>
            <p class="text" style="margin-top: 0; font-size: 30px">Всего товаров - {{ baskets.total_quantity }} шт.</p>


          {% for basket in baskets %}
              <div >
                  <div class="product_in" >
                      <div>
                        <h5 class="textbasket">{{ basket.product.name }}</h5>
                        <p class="textbasket1">{{ basket.product.description }}</p>
                      </div>
                      <ul style="list-style-type: none; padding: 0">
                        <li>
                          <div  align="center">
                                  <p class="textbasket1">{{ basket.quantity }}</p>
                          </div>
                            <div>
                                <span class="textbasket" >{{ basket.sum }} ♅</span>
                                <span><a href="{% url 'store:basket_remove' basket.id %}" class="basket_remove">
                                  <i class="fas fa-2x fa-trash"></i></a>
                                </span>
                            </div>

                        </li>
                      </ul>
                  </div>
            </div>
          {% endfor %}

        <div class="container1" style="border-radius: 60px; margin-top: 5px; height: 160px">
          <div>
            <p class="textbasket" style="margin-bottom: 0; margin-top: 0">Итого</p>
            <p class="textbasket" style="margin-bottom: 0; margin-top: 0">{{ baskets.total_sum }} ♅ </p>
              <button type="submit" class="btn_enter rounded" style="margin-bottom: 0"><span class="text-green">Оформить заказ</span></button>
          </div>
        </div>


      </div>
      <div>. </div>

{% else %}
        <div class="textbasket">Корзина пуста </div>
{% endif %}

backend/store/templates/store/main_page.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
    <div class="container" style=" margin-top: 100px; margin-bottom: 50px">
        <p align="center" class="text" >Акции <i
                style="color:white"
                class="fa-solid fa-comments-dollar"
                data-tippy-content="При добавлении в корзину акционных товаров, скидка 20%!"
        ></i></p>
                {% for product in object_list %}
                    {% if product.promo.promo == '1' %}
                        <div class="product-wrapper">
                            <div class="product" align="center">
                                <a class="name_product">{{product.name}}</a>
                                <span> <i style="float: right;color:white" class="fa-solid fa-2x fa-circle-exclamation"
                                data-tippy-content="{{ product.description }}
                                Количество - {{ product.quantity }} шт"></i></span>
                                <span> <i style="float: left;color:rgba(0,0,0, 0)" class="fa-solid fa-2x fa-circle-exclamation"></i></span>
                                <br>
                                <a href="{% url 'store:basket_add' product.id %}">
                                    <img align="center"
                                                 class="product-img"
                                                 src="{{ product.image.url }}"
                                                 data-tippy-content="Тыкни чтобы добавить в корзину"
                                ></a><br>
                                <a class="price" style="color: red">{{ product.price }} ♅</a>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
    </div>
    <div class="container1" >
        <p align="center" class="text">Ассортимент</p>

            {% for product in object_list %}
                <div class="product-wrapper">
                    <div class="product" align="center">
                        <a class="name_product">{{product.name}}</a>
                        <span> <i style="float: right;color:white" class="fa-solid fa-2x fa-circle-exclamation"
                        data-tippy-content="{{ product.description }}
                        Количество - {{ product.quantity }} шт"></i></span>
                        <span> <i style="float: left;color:rgba(0,0,0, 0)" class="fa-solid fa-2x fa-circle-exclamation"></i></span>
                        <br>
                        <a href="{% url 'store:basket_add' product.id %}">
                            <img align="center"
                                         class="product-img"
                                         src="{{ product.image.url }}"
                                         data-tippy-content="Тыкни чтобы добавить в корзину"
                        ></a><br>
                        <a class="price" {% if product.promo.promo == '1'%} style="color: red" {% endif %}
                        >{{ product.price }} ♅</a>
                    </div>
                </div>
            {% endfor %}

    </div>

<footer style="font-size: 20px; font-family: FontName; padding: 5px">
    <div style="float: left; margin-left: 20px; margin-top: 30px">Этот сайт не является настоящим магазином</div>
    <div style="float: right; margin-right: 20px">
        <a href="https://t.me/Chikcharyk">
            <img class="img_fo_footer"  src="{% static 'store/cat.jfif' %}">
        </a>
    </div>
    <br>
    <div style="margin-top: 50px; margin-left: 20px">Отдельная благодарность за стоковые изображения сайту </div>
     <a style="margin-left: 20px" href="https://www.flaticon.com/">https://www.flaticon.com/</a>

</footer>
{% endblock %}