backend/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products', ProductModelViewSet)
router.register(r'baskets', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from information.views import IndexView

static_urlpatterns = [

]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('information/', include('information.urls', namespace='information')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cosmicstore/', include('store.urls', namespace='cosmostore')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls', namespace='api')),
    path('tools/', include('tools.urls', namespace='tools')),
    path('api-token-auth/', views.obtain_auth_token),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/store/urls.py
from django.urls import path

from store.views import ProductsListView, basket_add, basket_remove

app_name = 'store'
urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    # path('category/<int:category_id>', ProductsListView.as_view(), name='category'), #категории пока не требуются
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
]

backend/users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from users.views import (EmailVerificationView, LogoutCustomView,
                         UserLoginView, UserProfileView, UserRegistrationView)

app_name = 'users'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registrations/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', login_required(UserProfileView.as_view()), name='profile'),
    path('logout/', LogoutCustomView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
]

backend/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    planet = models.CharField(max_length=256)
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self):
        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = 'Подтверждение учетной записи для {} перейдите по ссылке {}'.format(
            self.user.email,
            verification_link
        )
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

backend/users/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, UserChangeForm,
                                       UserCreationForm)

from users.models import User
from users.tasks import send_email_verification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ваше имя'}))
    planet = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'с какой вы планеты'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите ваш никнейм'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'type': 'text', 'placeholder': 'Введите вашу почту'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Повторите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'planet', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': ''}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

backend/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from users.models import EmailVerification, User


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Авторизация'

    def get_success_url(self):
        return reverse_lazy('store:index')


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Теперь вы в системе!'
    title = 'Регистрация'


class UserProfileView(TitleMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    title = 'Досье'

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.object.id,))


class LogoutCustomView(LogoutView):
    next_page = 'users:login'


class EmailVerificationView(TitleMixin, TemplateView):
    title = 'Подтверждение электронной почты'
    template_name = 'users/email_verification.html'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = User.objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)

        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('store:index'))

backend/users/templates/users/404_fo_users.html
{% load static %}
<div style="
background: #fff;
height: 100vh;
display: flex;
justify-content: center;
align-items: center;
">
    <div align="center">
        <span style="float: left; margin-left: 5%; margin-right: -5%"><img class="img404" src=" {% static '404/img/rocket.gif'%}"></span>
        <span style="float: right; margin-left: -5%; margin-right: 5%">
            <p style=" margin-bottom: -5px" align="center" class="text404">404</p>
            <p class="text404t">У Вас нет доступа к данной информации</p>
            <a style="text-decoration: none" href="{% url 'store:index' %}"><p class="text404s">Вернуться назад</p></a>
        </span>
    </div>
</div>

backend/users/templates/users/email_verification.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div style="
background: #fff;
height: 100vh;
display: flex;
justify-content: center;
align-items: center;
">
    <div align="center">
        <p class="text404t">Ваша учетная запись успешно подтверждена!</p>
        <a style="text-decoration: none" href="{% url 'store:index' %}"><p class="text404s">Вернуться назад</p></a>
        <img width="20%" src="{% static 'store/alien-dance.gif' %}">
    </div>
</div>
{% endblock %}

backend/users/templates/users/login.html
{% extends 'store/base.html' %}

{% load static %}

{% load socialaccount %}

{% block content %}

    <div align="center">
        {% if messages or form.non_field_errors %}
            <div class="alerts" id="message">
                    <span class="closebtn" onclick="this.parentElement.style.display='none';"> <i class="fa-solid fa-xmark"> </i> </span>
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% else %}
                        {{ form.non_field_errors }}
                    {% endif %}
            </div>
        {% endif %}
    </div>

<div class="container" >
  <p align="center" class="text"> Войди в систему космо торговли</p>
  <form class="modal-content" action="{% url 'users:login'%}" method = "post">
      {% csrf_token %}

    <label for="{{ form.username.id_for_label }}"><b class="textreg">Никнейм</b></label>
    {{ form.username }}

    <label for="{{ form.password.id_for_label }}"><b class="textreg">Пароль</b></label>
    {{ form.password }}


    <div align="center">
        <button type="submit" class="btn_enter rounded"><span class="text-green">Вход</span></button>
    </div>

    <h1 align="center" class="textreg">Или используйте другие системы</h1>

    <div class="col" align="center">
      <a href="#" class="fb btn">
        <i class="fa fa-facebook fa-2x fa-fw"></i>
      </a>
      <a href="{% provider_login_url 'github' %}" class="git btn">
        <i class="fa fa-github fa-2x fa-fw"></i>
      </a>
      <a href="#" class="google btn">
        <i class="fa fa-google fa-2x fa-fw"></i>
      </a>
    </div>
  </form>
  <h1 align="center"> <a href="{% url "users:registration" %}" class="ssreg">Нет в системе? Не беда! Тыкай быстро ты сюда<br> <img width="10%" src="{% static 'store/reg.gif' %}"></a></h1>
</div>

{% endblock %}

backend/users/templates/users/profile.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
    {% if request.user.id == user.id %}
        <div>
            <div class="container" style="width: 45%; float: left">
              <h1 class="text"  align="center" style="font-size: 30px">Ваш профиль в системе</h1>
              <form class="modal-content" action="{% url 'users:profile' user.id %}" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div align="center">
                  <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'store/cat.jfif' %} {% endif %}"
                       class="img-thumbnail">
                </div>
                <div align="center">
                  <label for ="{{ image.id_for_label}}" class="upload-file__label"></label>
                    {{ form.image }}
                </div>

                <label for="{{ form.email.id_for_label }}"><b class="textreg"> Email</b></label>
                {{ form.email }}

                <label for="{{ username.id_for_label}}"><b class="textreg">Никнейм</b></label>
                {{ form.username }}

                <label for="{{ form.last_name.id_for_label }}"><b class="textreg">Планета</b></label>
                {{ form.last_name }}

                <label for="{{ form.first_name.id_for_label }}"><b class="textreg">Ваше имя</b></label>
                {{ form.first_name }}

                <div class="clearfix" align="center">
                    <button type="submit" class="btn_enter rounded" style="margin-bottom: -100px"><span class="text-green">Сохранить</span></button>
                </div>
              </form>
            </div>
        </div>
        <div style="float: left; width: 45%" align="center">
            <div class="container" >
            {% include 'store/baskets.html' %}
            </div>
</div>

<footer>

</footer>


{% else %}
    {% include 'users/404_fo_users.html' %}
{% endif %}
{% endblock %}

backend/users/templates/users/registration.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}

<div align="center">
        {% if form.errors %}
            <div class="alerts" id="message" align="left">
                <span class="closebtn" onclick="this.parentElement.style.display='none';"> <i class="fa-solid fa-xmark"> </i> </span>
                <span>{{ form.errors }}</span>
            </div>
        {% endif %}
</div>

<div class="container">
  <p align="center" class="text"> Внесите себя в систему космо торговли</p>
  <form class="modal-content" action="{% url 'users:registration' %}" method="post">
      {% csrf_token %}

      <label for="{{ form.email.id_for_label }}"><b class="textreg" >Email
      </b></label>
      {{ form.email }}

      <label for="{{ form.username.id_for_label }}"><b class="textreg">Никнейм</b></label>
      {{ form.username }}

      <label for="{{ form.planet.id_for_label }}"><b class="textreg">Планета</b></label>
      {{ form.planet }}

      <label for="{{ form.first_name.id_for_label}}"><b class="textreg">Ваше имя</b></label>
      {{ form.first_name }}

      <label for="{{ form.password1.id_for_label }}"><b class="textreg">Пароль</b></label>
      {{ form.password1 }}

      <label for="{{ form.password2.id_for_label }}"><b class="textreg">Повторить пароль</b></label>
      {{ form.password2 }}

      <div class="clearfix" style="margin-bottom: -100px" align="center">
          <button type="submit" class="btn_enter rounded"><span class="text-green">Регистрация</span></button>
      </div>
  </form>
</div>

{% endblock %}